# Generated by Django 4.2.2 on 2023-06-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='files.uploadedfiles', verbose_name='Archivo'),
        ),
    ]
