# Generated by Django 4.2.2 on 2023-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_fileentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='Fecha de compra'),
        ),
    ]
