# Generated by Django 4.2.2 on 2023-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
    ]
